/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./*.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#fff8f5',
        'surface-container-highest': '#e9e1dc',
        'primary-container': '#6d5b98',
        'on-background': '#1e1b18',
        'tertiary-container': '#516c51',
        'primary-fixed-dim': '#d1bcff',
        'on-secondary-fixed-variant': '#4a4640',
        'surface-dim': '#e1d8d4',
        'on-tertiary-fixed': '#07200b',
        error: '#ba1a1a',
        'surface-tint': '#665491',
        secondary: '#625e57',
        'on-tertiary-fixed-variant': '#334d34',
        'surface-variant': '#e9e1dc',
        'inverse-primary': '#d1bcff',
        surface: '#fff8f5',
        'secondary-fixed': '#e8e1d9',
        'on-surface-variant': '#49454f',
        'on-tertiary-container': '#cdecc9',
        'secondary-container': '#e5dfd6',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#b0ceae',
        'surface-container-high': '#efe6e2',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#f8efea',
        'secondary-fixed-dim': '#ccc6bd',
        primary: '#54437e',
        tertiary: '#39543a',
        'surface-container-low': '#fbf2ed',
        background: '#fff8f5',
        'on-surface': '#1e1b18',
        'on-primary-fixed-variant': '#4e3d77',
        'on-secondary-container': '#66625b',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'primary-fixed': '#e9ddff',
        outline: '#7a7580',
        'on-primary-container': '#eadeff',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container': '#f5ece7',
        'inverse-surface': '#34302c',
        'on-secondary-fixed': '#1e1b16',
        'on-primary-fixed': '#210e49',
        'on-tertiary': '#ffffff',
        'outline-variant': '#cbc4d0',
        'tertiary-fixed': '#ccebc8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'container-max': '1280px',
        'margin-mobile': '20px',
        'stack-md': '24px',
        gutter: '32px',
        'stack-lg': '48px',
        unit: '8px',
        'stack-sm': '12px',
      },
      fontFamily: {
        'headline-xl': ['Noto Serif', 'serif'],
        'headline-lg': ['Noto Serif', 'serif'],
        'headline-sm': ['Noto Serif', 'serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'body-sm': ['Manrope', 'sans-serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'headline-md': ['Noto Serif', 'serif'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
